name: flutter_base
description: flutter_base_Project.
version: 1.0.4+5
publish_to: "none"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  dotted_border: ^2.1.0
  dropdown_search: ^5.0.6
  easy_localization: ^3.0.7
  equatable: ^2.0.7
  file_picker: ^8.1.5
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_colorpicker: ^1.1.0
  flutter_debouncer: ^2.0.0
  flutter_local_notifications: ^18.0.1
  flutter_offline: ^4.0.0
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.16
  flutter_timer_countdown: ^1.0.7
  fluttertoast: ^8.2.10
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  image_cropper: ^8.0.2
  image_picker: ^1.1.2
  intl: 0.19.0
  lottie: ^3.1.2
  multiple_result: ^5.1.0
  path_provider: ^2.1.3
  permission_handler: ^11.4.0
  photo_view: ^0.15.0
  pinput: ^5.0.0
  qr_code_scanner_plus: ^2.0.10+1
  share_plus: ^10.1.3
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  skeletonizer: ^1.4.2
  sliver_tools: ^0.2.12
  url_launcher: ^6.3.0
  watcher: ^1.1.0
  google_maps_flutter: ^2.4.0
  flutter_animate: ^4.5.2
  flutter_html: ^3.0.0
  pusher_channels_flutter: ^2.2.0
  webview_flutter: ^4.11.0
  flutter_pdfview: ^1.4.0+1
  video_player: ^2.9.5
  http: ^1.4.0
  multi_dropdown: ^3.0.1
  widgets_to_image: ^2.0.1
  audio_waveforms: ^1.3.0
  flutter_file_downloader: ^2.1.0
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0

dev_dependencies:
  change_app_package_name: ^1.5.0
  build_runner: null
  flutter_gen_runner: null
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/
    - assets/lottie/
    - assets/translations/

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets\fonts\SourceSansPro-Light.otf
          weight: 300
        - asset: assets\fonts\SourceSansPro-Regular.otf
          weight: 500
        - asset: assets\fonts\SourceSansPro-Semibold.otf
          weight: 700
        - asset: assets\fonts\SourceSansPro-Bold.otf
          weight: 900

flutter_gen:
  output: lib/src/config/res/
  line_length: 80
  integrations:
    lottie: true
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      class_name: AppAssets
